// <auto-generated />
using HK_Registration.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HK_ClassRegistration.Migrations
{
    [DbContext(typeof(CourseRegistrationContext))]
    partial class CourseRegistrationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("HK_Registration.Models.HKClass", b =>
                {
                    b.Property<int>("CourseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Credit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CourseID");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            CourseID = 1,
                            Capacity = 25,
                            Credit = 3,
                            Department = "Health Informatics",
                            Name = "Internet Programming",
                            Number = "CPSC-8720-02"
                        },
                        new
                        {
                            CourseID = 2,
                            Capacity = 20,
                            Credit = 4,
                            Department = "Computer Science",
                            Name = "Java Programming",
                            Number = "CPSC-8720-03"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
